[2024-10-16T09:38:14.382+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-10-16T09:38:14.405+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-10-16T09:38:14.406+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T09:38:14.408+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-10-16T09:38:14.409+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T09:38:14.439+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table_task> on 2024-07-05 00:00:00+00:00
[2024-10-16T09:38:14.446+0000] {standard_task_runner.py:55} INFO - Started process 3839 to run task
[2024-10-16T09:38:14.453+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_usd_rus_dag', 'create_table_task', 'scheduled__2024-07-05T00:00:00+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/RUS_DAG.py', '--cfg-path', '/tmp/tmpfouazfh_']
[2024-10-16T09:38:14.455+0000] {standard_task_runner.py:83} INFO - Job 278: Subtask create_table_task
[2024-10-16T09:38:14.561+0000] {task_command.py:389} INFO - Running <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-05T00:00:00+00:00 [running]> on host 63ee4fa64e74
[2024-10-16T09:38:14.616+0000] {abstractoperator.py:596} ERROR - Exception rendering Jinja template for task 'create_table_task', field 'sql'. Template: 'sql/create_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2024-10-16T09:38:14.619+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1497, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2119, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1196, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2024-10-16T09:38:14.633+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=exchange_rate_usd_rus_dag, task_id=create_table_task, execution_date=20240705T000000, start_date=20241016T093814, end_date=20241016T093814
[2024-10-16T09:38:14.654+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 278 for task create_table_task (sql/create_table.sql; 3839)
[2024-10-16T09:38:14.673+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-16T09:38:14.867+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T09:48:55.006+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-10-16T09:48:55.021+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-10-16T09:48:55.022+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T09:48:55.023+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-10-16T09:48:55.023+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T09:48:55.049+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table_task> on 2024-07-05 00:00:00+00:00
[2024-10-16T09:48:55.056+0000] {standard_task_runner.py:55} INFO - Started process 6524 to run task
[2024-10-16T09:48:55.066+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_usd_rus_dag', 'create_table_task', 'scheduled__2024-07-05T00:00:00+00:00', '--job-id', '1022', '--raw', '--subdir', 'DAGS_FOLDER/RUS_DAG.py', '--cfg-path', '/tmp/tmp87oe5b9c']
[2024-10-16T09:48:55.067+0000] {standard_task_runner.py:83} INFO - Job 1022: Subtask create_table_task
[2024-10-16T09:48:55.194+0000] {task_command.py:389} INFO - Running <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-05T00:00:00+00:00 [running]> on host 63ee4fa64e74
[2024-10-16T09:48:55.329+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rate_usd_rus_dag
AIRFLOW_CTX_TASK_ID=create_table_task
AIRFLOW_CTX_EXECUTION_DATE=2024-07-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-05T00:00:00+00:00
[2024-10-16T09:48:55.333+0000] {sql.py:253} INFO - Executing: CREATE TABLE IF NOT EXISTS currency_exchange_rates (
    base VARCHAR(3) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    rate NUMERIC(12, 3) NOT NULL,
    date DATE NOT NULL,
    UNIQUE (base, currency, date)
);
[2024-10-16T09:48:55.350+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-10-16T09:48:55.755+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-10-16T09:48:55.768+0000] {sql.py:364} INFO - Running statement: CREATE TABLE IF NOT EXISTS currency_exchange_rates (
    base VARCHAR(3) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    rate NUMERIC(12, 3) NOT NULL,
    date DATE NOT NULL,
    UNIQUE (base, currency, date)
);, parameters: None
[2024-10-16T09:48:55.788+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=exchange_rate_usd_rus_dag, task_id=create_table_task, execution_date=20240705T000000, start_date=20241016T094855, end_date=20241016T094855
[2024-10-16T09:48:55.823+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-10-16T09:48:55.886+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
